// Mocks generated by Mockito 5.0.10 from annotations
// in best_architecture_challenge/test/usecase_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:best_architecture_challenge/core/model/post.dart' as _i4;
import 'package:best_architecture_challenge/core/repository/post_repository_impl.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [PostRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRepositoryImpl extends _i1.Mock
    implements _i2.PostRepositoryImpl {
  MockPostRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Post>> fetchPosts() =>
      (super.noSuchMethod(Invocation.method(#fetchPosts, []),
              returnValue: Future<List<_i4.Post>>.value(<_i4.Post>[]))
          as _i3.Future<List<_i4.Post>>);
}
